// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://actiuqpkdzheotjcxknw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjdGl1cXBrZHpoZW90amN4a253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjExMzgsImV4cCI6MjA2NDI5NzEzOH0.BhSoV2Nv517BBRcdMbRwIcQVU9kXAhBpIwuKRqDTD3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);